services:
  postgres:
    image: postgres:16
    container_name: alibi_club-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${PSQL_DB}
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_USER_PASSWORD}
    volumes:
      - /volume1/docker/alibi_club/pgdata:/var/lib/postgresql/data
    networks: [appnet]

  server:
    build: ./server
    container_name: alibi_club-backend
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres
    networks: [appnet]
    expose:
      - "8000"

  client:
    image: nginx:alpine
    container_name: alibi_club-frontend
    restart: unless-stopped
    depends_on:
      - server
    volumes:
      - ./client/dist:/usr/share/nginx/html:ro
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks: [appnet]
    ports:
      - "8080:80"   # локально http://TNAS:8080

networks:
  appnet:
    driver: bridge
